server:
  port: ${GATEWAY_SERVICE_PORT:8089}

spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -
          id: RESOURCE
          uri: lb://RESOURCE
          predicates:
            - Path=/resources/**
        -
          id: SONG
          uri: lb://SONG
          predicates:
            - Path=/songs/**
        -
          id: STORAGE
          uri: lb://STORAGE
          predicates:
            - Path=/storages/**

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY:http://localhost:8088/eureka/}
