server:
  port: 8086

spring:
  application:
    name: SONG
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/song_service
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 5000
      validationTimeout: 2000
      maximumPoolSize: 5
      minimumIdle: 3
  liquibase:
    changeLog: classpath:db/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public

logging:
  level:
    liquibase: DEBUG
    com.epam.microservices.songservice: DEBUG
