server:
  port: ${STORAGE_SERVICE_PORT:8090}

spring:
  application:
    name: STORAGE
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${STORAGE_DB_HOST:localhost}:${STORAGE_DB_PORT:5434}/storage_service
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 5000
      validationTimeout: 2000
      maximumPoolSize: 5
      minimumIdle: 3
  liquibase:
    changeLog: classpath:db/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8888/realms/myrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: myclient
      principal-attribute: preferred_username

amazon:
  s3:
    endpoint: http://${AWS_HOST:localhost}:${AWS_PORT:4566}/
    region: us-east-1
    storages:
      -
        storageType: STAGING
        bucket: staging
        path: /temp
      -
        storageType: PERMANENT
        bucket: permanent
        path: /files

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY:http://localhost:8088/eureka/}
logging:
  level:
    liquibase: DEBUG
    com.epam.microservices.storageservice: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
