server:
  port: 8085

spring:
  application:
    name: RESOURCE
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices_fundamentals
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 5000
      validationTimeout: 2000
      maximumPoolSize: 5
      minimumIdle: 3
  liquibase:
    changeLog: classpath:db/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public

amazon:
  s3:
    bucket-name: test
    endpoint: http://localhost:4566/
    region: us-east-1
#    access-key: username
#    secret-key: password

logging:
  level:
    liquibase: DEBUG
    com.epam.microservices.resourseservice: DEBUG
