server:
  port: ${RESOURCE_SERVICE_PORT:8085}

spring:
  application:
    name: RESOURCE
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5432}/resource_service
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 5000
      validationTimeout: 2000
      maximumPoolSize: 5
      minimumIdle: 3
  liquibase:
    changeLog: classpath:db/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      resource-event-topic: resources
  cloud:
    openfeign:
      client:
        config:
          STORAGE:
            connect-timeout: 5000
            read-timeout: 5000
            loggerLevel: basic
            retryer: com.epam.microservices.resourceservice.feign.DefaultFeignRetryer
            error-decoder: com.epam.microservices.resourceservice.feign.Custom5xxErrorDecoder

amazon:
  s3:
    endpoint: http://${AWS_HOST:localhost}:${AWS_PORT:4566}/
    region: us-east-1

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY:http://localhost:8088/eureka/}
logging:
  level:
    liquibase: DEBUG
    com.epam.microservices.resourceservice: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
